/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.Views;

import App.Forms.FornecedoresForm;
import Models.Fornecedores;
import Persistencia.Generics;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Usuário
 */
public class FornecedoresView extends javax.swing.JInternalFrame {
    
    Fornecedores f = new Fornecedores();
    Generics generic = new Generics();
    ArrayList list = new ArrayList();
    DefaultTableModel modelo;
    /**
     * Creates new form FornecedoresView
     */
    public FornecedoresView() {
        initComponents();
        atualizaLista();
    }
    
    public void atualizaLista() {        
        String[] nomesColunas = {"ID", "Nome Fantasia", "Razão Social", "CNPJ"};        
        list = generic.getAll("fornecedores");        
        
        Object[][] dadosArray = new Object[list.size()][nomesColunas.length];
                
        for (int i = 0; i < list.size(); i++) {
            f = (Fornecedores) list.get(i);
            dadosArray[i][0] = f.getId();
            dadosArray[i][1] = f.getNomeFantasia();
            dadosArray[i][2] = f.getRazaoSocial();
            dadosArray[i][3] = f.getCNPJ();
        }                
        DefaultTableModel dm = new DefaultTableModel(dadosArray, nomesColunas);
        grdLista.setModel(dm);        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtFiltro = new javax.swing.JTextField();
        btnFiltro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdLista = new javax.swing.JTable();
        btnIncluirFornecedor = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluirFornecedor = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();

        setMaximizable(true);
        setTitle("Fornecedores");
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setName(""); // NOI18N

        txtFiltro.setToolTipText("Digite um id ou descrição e clique me pesquisar");
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });

        btnFiltro.setText("Filtro");
        btnFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroActionPerformed(evt);
            }
        });

        grdLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(grdLista);

        btnIncluirFornecedor.setText("Novo");
        btnIncluirFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirFornecedorActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluirFornecedor.setText("Excluir");
        btnExcluirFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirFornecedorActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFiltro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnIncluirFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtualizar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluirFornecedor)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluirFornecedor)
                    .addComponent(btnAtualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtFiltro.getAccessibleContext().setAccessibleName("Filtro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirFornecedorActionPerformed
        FornecedoresForm ff = new FornecedoresForm();
        ff.setVisible(true);
    }//GEN-LAST:event_btnIncluirFornecedorActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        this.atualizaLista();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroActionPerformed
       
    }//GEN-LAST:event_btnFiltroActionPerformed
    
    private Object getSelectedObject() {
        Object selecionado = null;
        int linhaSelecionada = grdLista.getSelectedRow();
        if (linhaSelecionada >= 0) {
            selecionado = list.get(linhaSelecionada);
        } else {
            JOptionPane.showMessageDialog(this, "Por gentileza, selecione um fornecedor.");
        }
        return selecionado;
    }
    
    public void Filtro(String filtro) {
        TableRowSorter sorter = new TableRowSorter(modelo);
        String regex = ".*" + filtro + ".*";
        sorter.setRowFilter(RowFilter.regexFilter(regex));
        grdLista.setRowSorter(sorter);

    }
    
    private void btnExcluirFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirFornecedorActionPerformed
        Object o = getSelectedObject();
        
        if (o != null) {
            f = (Fornecedores) o;
            String opcoes[] = {"Sim", "Não"};
            int opcao = JOptionPane.showOptionDialog(this, "Deseja remover esta forncedor: " + f.getNomeFantasia()+ "?",
                    "Confirma remoção", 0, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[1]);
            if (opcao == 0) {
                generic.delete(f);
                atualizaLista();
            }
        } 
    }//GEN-LAST:event_btnExcluirFornecedorActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Fornecedores obj = (Fornecedores)getSelectedObject();
                    
        FornecedoresForm ff = new FornecedoresForm(obj);
        ff.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        String filtro = txtFiltro.getText();
        Filtro(filtro);
    }//GEN-LAST:event_txtFiltroKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluirFornecedor;
    private javax.swing.JButton btnFiltro;
    private javax.swing.JButton btnIncluirFornecedor;
    private javax.swing.JTable grdLista;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
