/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import App.Views.CardapioView;
import App.Views.ClientesView;
import App.Views.FornecedoresView;
import App.Views.PedidosView;
import App.Views.ProdutosView;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Usuário
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        //setLayout(new BorderLayout());
        setVisible(true);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        dpMain.setBounds(this.getBounds());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpMain = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCadastros = new javax.swing.JMenu();
        mnClientes = new javax.swing.JMenuItem();
        mnFornecedores = new javax.swing.JMenuItem();
        mnProdutos = new javax.swing.JMenuItem();
        mnCardapio = new javax.swing.JMenuItem();
        mnPedidos = new javax.swing.JMenu();
        MenuItemPedidos = new javax.swing.JMenuItem();
        mnRelatorios = new javax.swing.JMenu();
        mnOpcoes = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dpMain.setMaximumSize(new java.awt.Dimension(1980, 1080));
        dpMain.setPreferredSize(new java.awt.Dimension(800, 500));
        //dpMain.setText("Cadastro");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Files/MainBackground.jpg"))); // NOI18N
        jLabel1.setText("jLabelMainBackuground");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dpMain.add(jLabel1);
        jLabel1.setBounds(0, 0, 2137, 1320);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        dpMain.add(jPanel1);
        jPanel1.setBounds(190, 130, 100, 100);

        jMenuBar1.setMaximumSize(new java.awt.Dimension(222, 600));

        mnCadastros.setText("Cadastros");
        mnCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrosActionPerformed(evt);
            }
        });

        mnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Files/multiple-users-silhouette.png"))); // NOI18N
        mnClientes.setText("Clientes");
        mnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnClientesActionPerformed(evt);
            }
        });
        mnCadastros.add(mnClientes);

        mnFornecedores.setText("Fornecedores");
        mnFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFornecedoresActionPerformed(evt);
            }
        });
        mnCadastros.add(mnFornecedores);

        mnProdutos.setText("Produtos");
        mnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnProdutosActionPerformed(evt);
            }
        });
        mnCadastros.add(mnProdutos);

        mnCardapio.setText("Cardápio");
        mnCardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCardapioActionPerformed(evt);
            }
        });
        mnCadastros.add(mnCardapio);

        jMenuBar1.add(mnCadastros);

        mnPedidos.setText("Pedidos");

        MenuItemPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Files/shopping-cart.png"))); // NOI18N
        MenuItemPedidos.setText("Pedidos");
        MenuItemPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemPedidosActionPerformed(evt);
            }
        });
        mnPedidos.add(MenuItemPedidos);

        jMenuBar1.add(mnPedidos);

        mnRelatorios.setText("Relatórios");
        jMenuBar1.add(mnRelatorios);

        mnOpcoes.setText("Opções");
        mnOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpcoesActionPerformed(evt);
            }
        });

        mnSair.setText("Sair");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        mnOpcoes.add(mnSair);

        jMenuBar1.add(mnOpcoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpcoesActionPerformed
        
    }//GEN-LAST:event_mnOpcoesActionPerformed

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed

        System.exit(0);
    }//GEN-LAST:event_mnSairActionPerformed

    private void mnCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrosActionPerformed
        
    }//GEN-LAST:event_mnCadastrosActionPerformed

    private void mnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnClientesActionPerformed
        ClientesView cv = new ClientesView();
        dpMain.add(cv);
        
        cv.toBack();
        cv.setVisible(true);
        cv.setClosable(true);
        try {
            cv.setMaximum(true);
        } catch (Exception e) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_mnClientesActionPerformed

    private void mnFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFornecedoresActionPerformed
        FornecedoresView fornecedoresView = new FornecedoresView();
        
        dpMain.add(fornecedoresView);
        
        fornecedoresView.toBack();
        fornecedoresView.setVisible(true);
        fornecedoresView.setClosable(true);
        try {
            fornecedoresView.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnFornecedoresActionPerformed

    private void mnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnProdutosActionPerformed
        ProdutosView pv = new ProdutosView();
        
        dpMain.add(pv);

        pv.toBack();
        pv.setVisible(true);
        pv.setClosable(true);
        
        try {
            pv.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnProdutosActionPerformed

    private void mnCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCardapioActionPerformed
        CardapioView cv = new CardapioView();
        dpMain.add(cv);
        
        cv.toBack();
        cv.setVisible(true);
        cv.setClosable(true);
        
        try {
            cv.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnCardapioActionPerformed

    private void MenuItemPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemPedidosActionPerformed
      PedidosView cv = new PedidosView();
        dpMain.add(cv);
        
        cv.toBack();
        cv.setVisible(true);
        cv.setClosable(true);
        
        try {
            cv.setMaximum(false);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MenuItemPedidosActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemPedidos;
    private javax.swing.JDesktopPane dpMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnCadastros;
    private javax.swing.JMenuItem mnCardapio;
    private javax.swing.JMenuItem mnClientes;
    private javax.swing.JMenuItem mnFornecedores;
    private javax.swing.JMenu mnOpcoes;
    private javax.swing.JMenu mnPedidos;
    private javax.swing.JMenuItem mnProdutos;
    private javax.swing.JMenu mnRelatorios;
    private javax.swing.JMenuItem mnSair;
    // End of variables declaration//GEN-END:variables
}
